import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const Azahar = localFont({
  src: [
    {
      path: "../fonts/Azahar.ttf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-azahar",
});
const Zahir_Arabic = localFont({
  src: [
    {
      path: "../fonts/Zahir_Arabic.otf",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-zahir",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${geistSans.variable} ${Azahar.variable} ${Zahir_Arabic.variable}  ${geistMono.variable}`}>
      <body>{children}</body>
    </html>
  );
}
